### ISSUE TITLE
[FR] Camera snapshot url invalid header validation

### ISSUE THREAD

**Issue by miguelangel-nubla** [jakowenko/double-take#127] opened 2021-10-13 20:24 UTC
I have configured the [custom snapshot url per camera](https://github.com/jakowenko/double-take/commit/e2f93e63d0f7031b92690e612f9b57d28ebe4adc) feature.
The camera returns the header `Content-Type: image/jpeg; charset="UTF-8"` and double-take chokes on the charset part.
```
error: url validation failed for snapshot: http://url:port/ISAPI/Streaming/Channels/1/picture - image/jpeg; charset="UTF-8" not valid
```
It is not exactly textbook behavior but I don't think hikvision is going to fix the firmware anytime soon, so maybe ignoring the charset part is a good idea?

**Hardware**
 - Annke C800 flashed with the latest official hikvision firmware (so I guess affects every hikvision camera)

**Comment by jakowenko** [comment] 2021-10-14 00:11
Thanks for reporting this. It should be easy enough to reproduce and fix. I should be able to get a new beta build up tonight.

**Comment by jakowenko** [comment] 2021-10-14 02:08
New beta build should be ready in an hour. I'll update this post when it includes the fix.

**Comment by jakowenko** [comment] 2021-10-19 03:37
I'm going to close this since `1.5.0` fixed the content type issue. Feel free to reopen if you run into problems with it.

**Closed by jakowenko** 2021-10-19 03:37 UTC
Labels: bug
