### ISSUE TITLE
objects.face.min_area_match

### ISSUE THREAD

**Issue by Sborkahome** [jakowenko/double-take#58] opened 2021-06-19 09:54 UTC
David, hi!
In config.yml is parameter -  objects.face.min_area_match: 15000
When frigate captures images, double-take compares them all in a row. And can you make double-take compare only those that fit the specified "Box" parameters? 
Why compare those images when they do not match those specified in config.yml. 
For example, here double-take makes 3 unnecessary comparisons when "Box" is smaller than the parameter objects.face.min_area_match: 15000

![image](https://user-images.githubusercontent.com/26301036/122638461-dd6a4f80-d0fc-11eb-9a08-8924369eb25a.png)

**Comment by jakowenko** [comment] 2021-06-19 13:09
Hey @Sborkahome,

The `objects.face.min_area_match` parameter only determines if it should be considered a match. The image will still be saved, but if it's smaller than the size configured it won't be a match. I can add another option if you'd like to make it not even save these images.

**Comment by jakowenko** [comment] 2021-06-23 05:46
I'm going to close this since it's working as intended. Feel free to open a new issue if you encounter any other problems.

**Closed by jakowenko** 2021-06-23 05:46 UTC
