### ISSUE TITLE
Mqtt snapshots and Config cameras 

### ISSUE THREAD

**Issue by Raphael909** [jakowenko/double-take#49] opened 2021-06-05 19:31 UTC
Hello @jakowenko , Not sure if you are noticing this also but after installing 0.6 release, I am like seeing few odds stuff:

- Mqtt subscription for snapshot not honoring the cameras present in config yml. Instead it seems to process every entity sent by frigate . May be because of 'frigate/cameras/+/person/snapshots'. 
- Config has minimum match confidence of 95 but UI does not think a recognition of 99% as match or say. anything greater than 95% as match. Only at 95.xx% tag is set to green otherwise it remains red.
- Updated HA to latest and it seems like  double-take might have stopped publishing sensor data via API

As always, thank you for your time and effort!

**Comment by jakowenko** [comment] 2021-06-07 01:02
Hey @Raphael909, I have a new beta build to fix the MQTT snapshots not honoring the Frigate camera config. Good catch on that, I missed it when adding in that feature.

I haven't been able to reproduce the confidence issue you are describing. Can you double check your config and post what you have here for that section? I tested the following image three times. First with 50% confidence, then 95%, then 101% just to make sure no matches were returned. The results from each attempt reproduced the right color on the UI.

<img width="1042" alt="Screen Shot 2021-06-06 at 8 54 59 PM" src="https://user-images.githubusercontent.com/1081811/120946392-4ff52b80-c70a-11eb-98bd-e7a2a250ce06.png">

I'm on the most recent version of HA and entitles are still being published for me. Are you still experiencing issues?

**Comment by Raphael909** [comment] 2021-06-07 01:40
Thank you for the quick fix . Part of the config:
`mqtt:
  host: 192.168.xx.xx
  username: "mqtt"
  password: "1982"
  topics:
    frigate: frigate/events
    matches: double-take/matches
    cameras: double-take/cameras

home_assistant:
  url: http://192.168.xx.xx:8123
  token: ${token}
confidence:
  match: 95
  unknown: 60

objects:
  face:
    min_area_match: 10000

save:
  matches: true
  unknown: true

purge:
  matches: 8
  unknown: 8

frigate:
  url: http://192.168.xx.xx:5000
  image:
    height: 500
  attempts:
    latest: 2
    snapshot: 0
  cameras:
    - doorbell
    - garage
    - driveway
    `
- Looks like I might have wrong understanding of how UI works... Your first image from the test has marked compreface as red  for David 100% but in the rest it is marked green. I thought % is confidence level from compreface.
- for some reason I still don't see entities getting update in HA. In fact, I no longer see entity with sensor_double_take_xxx.
- Also, I don't get Mqtt updates . hmm something is not happy in my setup it seems.

**Comment by jakowenko** [comment] 2021-06-07 02:24
The images in my screenshot really read from right to left with the percentages I posted. The left one was red at 100% because I set the value in the config to 101, so any images less than 101% are not considered a match.

When a match is found from a detector the confidence value from that result is compared with the one set in the config. For example, if a result comes back from CompreFace with a percent of 50%, then this value is compared with the one set in the config to determine if the result should be considered a match. The red/green in the UI is based off the image being considered a "match" from each detector.

Based on your suggestion from #38, I'm going to drop the HA direct API integration in favor of MQTT with a retain flag. I already have the updates ready and I'm about to push up the beta build. It's really nice to have the state in HA with restarts now.

**Comment by jakowenko** [comment] 2021-06-08 14:38
@Raphael909 am I good to close this issue or are you still having issues?

**Comment by Raphael909** [comment] 2021-06-09 03:41
@jakowenko , sorry man, my PSU failed on me the other day so never got it tested . It is on the way  but anyways I will close this issue for now.
Thank your again!

**Closed** 2021-06-09 03:41 UTC

**Comment by jakowenko** [comment] 2021-06-09 03:49
No worries, thank you. Hope you get that PSU fixed soon 🤞
